### ISSUE TITLE
Only Flovatar collection working

### ISSUE THREAD

**Issue by lokapujya** [Outblock/flow-api#1]
Running on localhost.
/api/nft/collection?collectionIdentifier=Flovatar 
works, but other collectionIdentifiers such as Golazos give an  an Invalid Flow argument error

**Comment by lmcmz** [comment]
Could you double check the id match the records in NFT catalog ?
From what I can see the id should be `LaligaGolazos`.
http://localhost:3000/api/nft/collection?collectionIdentifier=LaligaGolazos
